export type ExerciseLang = "js" | "web" | "python" | "sql" | "java" | "c";

export type Exercise = {
  id: string;
  title: string;
  lang: ExerciseLang;
  difficulty: "Facile" | "Moyen" | "Difficile";
  /** Notion de leçon mise en pratique. */
  concept: string;
  prompt: string;
  starter: string;
  solution: string;
  hint: string;
  /** Sortie console attendue (comparée après normalisation). */
  expected?: string;
  /** Vérification personnalisée (appliquée sur la sortie console, ou sur le code pour le web). */
  check?: (value: string) => boolean;
};

export const exerciseLangs: { id: ExerciseLang; label: string; runnable: boolean }[] = [
  { id: "js", label: "JavaScript", runnable: true },
  { id: "web", label: "HTML/CSS", runnable: true },
  { id: "python", label: "Python", runnable: true },
  { id: "sql", label: "SQL", runnable: true },
  { id: "java", label: "Java", runnable: false },
  { id: "c", label: "C", runnable: false },
];

export const difficulties = ["Tous", "Facile", "Moyen", "Difficile"] as const;

export const exercises: Exercise[] = [
  /* ----------------------------- JavaScript ----------------------------- */
  {
    id: "js-somme",
    title: "La somme",
    lang: "js",
    difficulty: "Facile",
    concept: "Variables & opérateurs",
    prompt: "Affiche dans la console la somme de 5 et 3. Résultat attendu : 8.",
    starter: "// Affiche la somme de 5 et 3\nconsole.log( );",
    solution: "// Affiche la somme de 5 et 3\nconsole.log(5 + 3);",
    hint: "L'addition s'écrit avec +. Place 5 + 3 entre les parenthèses de console.log.",
    expected: "8",
  },
  {
    id: "js-boucle",
    title: "Compte de 1 à 5",
    lang: "js",
    difficulty: "Facile",
    concept: "Boucles for",
    prompt: "Affiche les nombres de 1 à 5, un par ligne.",
    starter: "// Affiche les nombres de 1 à 5\n",
    solution: "for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}",
    hint: "Une boucle for (let i = 1; i <= 5; i++) répète l'affichage de i.",
    expected: "1\n2\n3\n4\n5",
  },
  {
    id: "js-fonction",
    title: "La fonction carré",
    lang: "js",
    difficulty: "Moyen",
    concept: "Fonctions & return",
    prompt: "Complète la fonction carre pour qu'elle renvoie le carré de n, puis affiche carre(4) (résultat : 16).",
    starter: "function carre(n) {\n  // renvoie n multiplié par lui-même\n}\n\nconsole.log(carre(4));",
    solution: "function carre(n) {\n  return n * n;\n}\n\nconsole.log(carre(4));",
    hint: "Utilise return n * n; à l'intérieur de la fonction.",
    expected: "16",
  },
  {
    id: "js-pairs",
    title: "Les nombres pairs",
    lang: "js",
    difficulty: "Moyen",
    concept: "Conditions & boucles",
    prompt: "Affiche uniquement les nombres pairs de 2 à 10, un par ligne.",
    starter: "// Affiche les pairs de 2 à 10\n",
    solution: "for (let i = 2; i <= 10; i += 2) {\n  console.log(i);\n}",
    hint: "Tu peux compter de 2 en 2 avec i += 2, en partant de 2.",
    expected: "2\n4\n6\n8\n10",
  },
  {
    id: "js-table",
    title: "Table de multiplication",
    lang: "js",
    difficulty: "Moyen",
    concept: "Boucles & template strings",
    prompt: "Affiche la table de 3, de 3 x 1 à 3 x 5, au format « 3 x i = résultat ».",
    starter: "// Affiche la table de 3 de 1 à 5\n",
    solution: "for (let i = 1; i <= 5; i++) {\n  console.log(`3 x ${i} = ${3 * i}`);\n}",
    hint: "Utilise une template string : `3 x ${i} = ${3 * i}`.",
    expected: "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15",
  },
  {
    id: "js-max",
    title: "Le plus grand",
    lang: "js",
    difficulty: "Facile",
    concept: "Fonctions & conditions",
    prompt: "Complète la fonction max pour qu'elle renvoie le plus grand de deux nombres, puis affiche max(12, 7) (résultat : 12).",
    starter: "function max(a, b) {\n  // renvoie le plus grand\n}\n\nconsole.log(max(12, 7));",
    solution: "function max(a, b) {\n  return a > b ? a : b;\n}\n\nconsole.log(max(12, 7));",
    hint: "Une condition ternaire : return a > b ? a : b;.",
    expected: "12",
  },
  {
    id: "js-somme-tableau",
    title: "Somme d'un tableau",
    lang: "js",
    difficulty: "Moyen",
    concept: "Tableaux & boucles",
    prompt: "Calcule la somme de toutes les notes du tableau, puis affiche-la (résultat : 66).",
    starter: "const notes = [4, 8, 15, 16, 23];\nlet total = 0;\n// additionne toutes les notes\nconsole.log(total);",
    solution: "const notes = [4, 8, 15, 16, 23];\nlet total = 0;\nfor (const n of notes) total += n;\nconsole.log(total);",
    hint: "Parcours le tableau avec for (const n of notes) et ajoute chaque valeur à total.",
    expected: "66",
  },
  {
    id: "js-objet",
    title: "Présente un étudiant",
    lang: "js",
    difficulty: "Moyen",
    concept: "Objets littéraux",
    prompt: "À partir de l'objet etudiant, affiche la phrase « Alex a 25 ans ».",
    starter: 'const etudiant = { nom: "Alex", age: 25 };\n// affiche "Alex a 25 ans"\n',
    solution: "const etudiant = { nom: \"Alex\", age: 25 };\nconsole.log(`${etudiant.nom} a ${etudiant.age} ans`);",
    hint: "Accède aux champs avec etudiant.nom et etudiant.age dans une template string.",
    expected: "Alex a 25 ans",
  },
  {
    id: "js-voyelles",
    title: "Compter les voyelles",
    lang: "js",
    difficulty: "Moyen",
    concept: "Chaînes & boucles",
    prompt: "Compte le nombre de voyelles dans « bonjour » (résultat : 3).",
    starter: 'const mot = "bonjour";\nlet voyelles = 0;\n// compte les voyelles (a,e,i,o,u)\nconsole.log(voyelles);',
    solution: 'const mot = "bonjour";\nlet voyelles = 0;\nfor (const l of mot) {\n  if ("aeiou".includes(l)) voyelles++;\n}\nconsole.log(voyelles);',
    hint: "Parcours chaque lettre et incrémente voyelles si \"aeiou\".includes(lettre).",
    expected: "3",
  },
  {
    id: "js-palindrome",
    title: "C'est un palindrome ?",
    lang: "js",
    difficulty: "Difficile",
    concept: "Méthodes de chaîne",
    prompt: "Affiche true si « kayak » est un palindrome, false sinon (résultat : true).",
    starter: 'const mot = "kayak";\n// affiche true si c\'est un palindrome\n',
    solution: 'const mot = "kayak";\nconsole.log(mot === mot.split("").reverse().join(""));',
    hint: "Inverse la chaîne avec split(\"\").reverse().join(\"\") puis compare-la au mot d'origine.",
    expected: "true",
  },
  {
    id: "js-premier",
    title: "Nombre premier",
    lang: "js",
    difficulty: "Difficile",
    concept: "Boucles & conditions",
    prompt: "Complète estPremier(n) pour qu'elle renvoie true si n est premier, puis affiche estPremier(7) (résultat : true).",
    starter: "function estPremier(n) {\n  // renvoie true si n est premier (n > 1)\n}\n\nconsole.log(estPremier(7));",
    solution: "function estPremier(n) {\n  if (n < 2) return false;\n  for (let i = 2; i < n; i++) {\n    if (n % i === 0) return false;\n  }\n  return true;\n}\n\nconsole.log(estPremier(7));",
    hint: "Si n est divisible par un i entre 2 et n-1, ce n'est pas premier (return false).",
    expected: "true",
  },
  {
    id: "js-fizzbuzz",
    title: "Le défi FizzBuzz",
    lang: "js",
    difficulty: "Difficile",
    concept: "Conditions combinées",
    prompt: "Pour les nombres de 1 à 15 : affiche « Fizz » si divisible par 3, « Buzz » si divisible par 5, « FizzBuzz » si par les deux, sinon le nombre.",
    starter: "// FizzBuzz de 1 à 15\n",
    solution: 'for (let i = 1; i <= 15; i++) {\n  if (i % 3 === 0 && i % 5 === 0) console.log("FizzBuzz");\n  else if (i % 3 === 0) console.log("Fizz");\n  else if (i % 5 === 0) console.log("Buzz");\n  else console.log(i);\n}',
    hint: "Teste d'abord le cas « divisible par 3 ET 5 » (FizzBuzz), puis 3, puis 5, sinon le nombre.",
    expected: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz",
  },

  /* ------------------------------ HTML / CSS ------------------------------ */
  {
    id: "web-titre",
    title: "Ton premier titre",
    lang: "web",
    difficulty: "Facile",
    concept: "Balises HTML",
    prompt: "Ajoute un titre de niveau 1 (h1) contenant le texte « Bonjour le web ».",
    starter: "<h1></h1>",
    solution: "<h1>Bonjour le web</h1>",
    hint: "Place le texte entre <h1> et </h1>.",
    check: (code) => /<h1>[^<]+<\/h1>/i.test(code),
  },
  {
    id: "web-couleur",
    title: "Texte en couleur",
    lang: "web",
    difficulty: "Facile",
    concept: "CSS couleur",
    prompt: "Donne une couleur (par exemple rouge) au paragraphe avec l'attribut style.",
    starter: '<p style="">Je suis un texte.</p>',
    solution: '<p style="color: red;">Je suis un texte.</p>',
    hint: "Ajoute color: red; dans l'attribut style.",
    check: (code) => /color\s*:/i.test(code),
  },
  {
    id: "web-liste",
    title: "Une liste à puces",
    lang: "web",
    difficulty: "Moyen",
    concept: "Listes HTML",
    prompt: "Crée une liste à puces (ul) avec deux éléments (li) : Pomme et Poire.",
    starter: "<ul>\n  \n</ul>",
    solution: "<ul>\n  <li>Pomme</li>\n  <li>Poire</li>\n</ul>",
    hint: "Chaque élément s'écrit <li>texte</li> à l'intérieur du <ul>.",
    check: (code) => (code.match(/<li>/gi) || []).length >= 2,
  },
  {
    id: "web-lien",
    title: "Un lien cliquable",
    lang: "web",
    difficulty: "Facile",
    concept: "Liens (a href)",
    prompt: "Transforme ce lien pour qu'il pointe vers https://example.com grâce à l'attribut href.",
    starter: "<a>Voir le site</a>",
    solution: '<a href="https://example.com">Voir le site</a>',
    hint: "Ajoute href=\"https://example.com\" à la balise <a>.",
    check: (code) => /href\s*=/i.test(code),
  },
  {
    id: "web-image",
    title: "Une image accessible",
    lang: "web",
    difficulty: "Facile",
    concept: "Images & alt",
    prompt: "Ajoute l'attribut alt « Logo » à cette image pour l'accessibilité.",
    starter: '<img src="logo.png">',
    solution: '<img src="logo.png" alt="Logo">',
    hint: "Ajoute alt=\"Logo\" dans la balise <img>.",
    check: (code) => /alt\s*=/i.test(code),
  },
  {
    id: "web-bouton",
    title: "Styliser un bouton",
    lang: "web",
    difficulty: "Moyen",
    concept: "Style CSS",
    prompt: "Donne un style au bouton : fond orange, texte blanc, un peu de padding et des bords arrondis.",
    starter: "<button>Clique-moi</button>",
    solution: '<button style="background: #ff6b47; color: white; padding: 10px 20px; border: none; border-radius: 8px;">Clique-moi</button>',
    hint: "Ajoute un attribut style avec background, color, padding et border-radius.",
    check: (code) => /style\s*=/i.test(code),
  },
  {
    id: "web-carte",
    title: "Une carte de profil",
    lang: "web",
    difficulty: "Moyen",
    concept: "Box model & couleur",
    prompt: "Donne au conteneur un fond coloré et un peu de padding pour former une carte.",
    starter: '<div style="">\n  <h2>Mon profil</h2>\n  <p>Développeur en devenir.</p>\n</div>',
    solution: '<div style="background: #fff3e0; padding: 24px; border-radius: 12px;">\n  <h2>Mon profil</h2>\n  <p>Développeur en devenir.</p>\n</div>',
    hint: "Dans le style du <div>, ajoute background, padding et border-radius.",
    check: (code) => /background/i.test(code),
  },
  {
    id: "web-flex",
    title: "Aligner en ligne (Flexbox)",
    lang: "web",
    difficulty: "Moyen",
    concept: "Flexbox",
    prompt: "Affiche les trois boîtes côte à côte grâce à Flexbox.",
    starter: '<div style="">\n  <div>1</div>\n  <div>2</div>\n  <div>3</div>\n</div>',
    solution: '<div style="display: flex; gap: 12px;">\n  <div>1</div>\n  <div>2</div>\n  <div>3</div>\n</div>',
    hint: "Ajoute display: flex; (et gap pour l'espacement) dans le style du conteneur.",
    check: (code) => /display:\s*flex/i.test(code),
  },
  {
    id: "web-formulaire",
    title: "Un mini formulaire",
    lang: "web",
    difficulty: "Difficile",
    concept: "Formulaires HTML",
    prompt: "Ajoute un champ de saisie (input) et un bouton « Envoyer » dans ce formulaire.",
    starter: "<form>\n  \n</form>",
    solution: '<form>\n  <input type="text" placeholder="Votre nom">\n  <button>Envoyer</button>\n</form>',
    hint: "Place une balise <input> et une balise <button> à l'intérieur du <form>.",
    check: (code) => /<input/i.test(code) && /<button/i.test(code),
  },
  {
    id: "web-grid",
    title: "Une grille (CSS Grid)",
    lang: "web",
    difficulty: "Difficile",
    concept: "CSS Grid",
    prompt: "Affiche les éléments en une grille de 3 colonnes égales avec CSS Grid.",
    starter: '<div style="">\n  <div>A</div>\n  <div>B</div>\n  <div>C</div>\n</div>',
    solution: '<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px;">\n  <div>A</div>\n  <div>B</div>\n  <div>C</div>\n</div>',
    hint: "Ajoute display: grid; et grid-template-columns: 1fr 1fr 1fr; dans le style.",
    check: (code) => /display:\s*grid/i.test(code),
  },

  /* ------------------------------- Python ------------------------------- */
  {
    id: "py-somme",
    title: "La somme",
    lang: "python",
    difficulty: "Facile",
    concept: "print & opérateurs",
    prompt: "Affiche la somme de 5 et 3 (résultat : 8).",
    starter: "# Affiche la somme de 5 et 3\nprint( )",
    solution: "# Affiche la somme de 5 et 3\nprint(5 + 3)",
    hint: "Place 5 + 3 entre les parenthèses de print.",
    expected: "8",
  },
  {
    id: "py-boucle",
    title: "Compte de 1 à 5",
    lang: "python",
    difficulty: "Facile",
    concept: "Boucles for & range",
    prompt: "Affiche les nombres de 1 à 5, un par ligne.",
    starter: "# Affiche les nombres de 1 à 5\n",
    solution: "for i in range(1, 6):\n    print(i)",
    hint: "Utilise for i in range(1, 6): puis print(i) indenté.",
    expected: "1\n2\n3\n4\n5",
  },
  {
    id: "py-fstring",
    title: "Saluer quelqu'un",
    lang: "python",
    difficulty: "Moyen",
    concept: "f-strings",
    prompt: 'Crée une variable nom = "Alex" puis affiche « Bonjour Alex » avec une f-string.',
    starter: 'nom = "Alex"\n# affiche Bonjour Alex\n',
    solution: 'nom = "Alex"\nprint(f"Bonjour {nom}")',
    hint: 'Une f-string s\'écrit f"Bonjour {nom}".',
    expected: "Bonjour Alex",
  },
  {
    id: "py-pairs",
    title: "Les nombres pairs",
    lang: "python",
    difficulty: "Moyen",
    concept: "range avec pas",
    prompt: "Affiche les nombres pairs de 2 à 10, un par ligne.",
    starter: "# Affiche les pairs de 2 à 10\n",
    solution: "for i in range(2, 11, 2):\n    print(i)",
    hint: "range(2, 11, 2) va de 2 à 10 de 2 en 2.",
    expected: "2\n4\n6\n8\n10",
  },
  {
    id: "py-max",
    title: "La plus grande note",
    lang: "python",
    difficulty: "Facile",
    concept: "Listes & fonctions",
    prompt: "Affiche la plus grande note de la liste (résultat : 9).",
    starter: "notes = [3, 9, 2]\n# affiche la plus grande note\n",
    solution: "notes = [3, 9, 2]\nprint(max(notes))",
    hint: "La fonction max() renvoie le plus grand élément d'une liste.",
    expected: "9",
  },
  {
    id: "py-somme-liste",
    title: "Somme d'une liste",
    lang: "python",
    difficulty: "Facile",
    concept: "sum() & listes",
    prompt: "Affiche la somme des notes (résultat : 66).",
    starter: "notes = [4, 8, 15, 16, 23]\n# affiche la somme\n",
    solution: "notes = [4, 8, 15, 16, 23]\nprint(sum(notes))",
    hint: "La fonction sum() additionne tous les éléments d'une liste.",
    expected: "66",
  },
  {
    id: "py-table",
    title: "Table de multiplication",
    lang: "python",
    difficulty: "Moyen",
    concept: "Boucles & f-strings",
    prompt: "Affiche la table de 3, de 3 x 1 à 3 x 5, au format « 3 x i = résultat ».",
    starter: "# Affiche la table de 3 de 1 à 5\n",
    solution: 'for i in range(1, 6):\n    print(f"3 x {i} = {3 * i}")',
    hint: 'Boucle range(1, 6) et f-string f"3 x {i} = {3 * i}".',
    expected: "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15",
  },
  {
    id: "py-dictionnaire",
    title: "Présenter un étudiant",
    lang: "python",
    difficulty: "Moyen",
    concept: "Dictionnaires",
    prompt: "À partir du dictionnaire etudiant, affiche la phrase « Alex a 25 ans ».",
    starter: 'etudiant = {"nom": "Alex", "age": 25}\n# affiche "Alex a 25 ans"\n',
    solution: 'etudiant = {"nom": "Alex", "age": 25}\nprint(f"{etudiant[\'nom\']} a {etudiant[\'age\']} ans")',
    hint: "Accède aux valeurs avec etudiant['nom'] et etudiant['age'] dans une f-string.",
    expected: "Alex a 25 ans",
  },
  {
    id: "py-puissance",
    title: "Fonction puissance",
    lang: "python",
    difficulty: "Moyen",
    concept: "Fonctions",
    prompt: "Complète la fonction puissance(x, n) pour qu'elle renvoie x à la puissance n, puis affiche puissance(2, 10) (résultat : 1024).",
    starter: "def puissance(x, n):\n    # renvoie x à la puissance n\n    pass\n\nprint(puissance(2, 10))",
    solution: "def puissance(x, n):\n    return x ** n\n\nprint(puissance(2, 10))",
    hint: "L'opérateur puissance est ** : return x ** n.",
    expected: "1024",
  },
  {
    id: "py-voyelles",
    title: "Compter les voyelles",
    lang: "python",
    difficulty: "Moyen",
    concept: "Boucles & conditions",
    prompt: "Compte le nombre de voyelles dans « bonjour » (résultat : 3).",
    starter: 'mot = "bonjour"\nvoyelles = 0\n# compte les voyelles (a,e,i,o,u)\nprint(voyelles)',
    solution: 'mot = "bonjour"\nvoyelles = 0\nfor lettre in mot:\n    if lettre in "aeiou":\n        voyelles += 1\nprint(voyelles)',
    hint: "Parcours chaque lettre et incrémente si lettre in \"aeiou\".",
    expected: "3",
  },
  {
    id: "py-palindrome",
    title: "C'est un palindrome ?",
    lang: "python",
    difficulty: "Difficile",
    concept: "Tranches de chaîne",
    prompt: "Affiche True si « kayak » est un palindrome (résultat : True).",
    starter: 'mot = "kayak"\n# affiche True si palindrome\n',
    solution: 'mot = "kayak"\nprint(mot == mot[::-1])',
    hint: "La tranche mot[::-1] renvoie la chaîne inversée.",
    expected: "True",
  },
  {
    id: "py-fizzbuzz",
    title: "Le défi FizzBuzz",
    lang: "python",
    difficulty: "Difficile",
    concept: "Conditions combinées",
    prompt: "Pour les nombres de 1 à 15 : affiche « Fizz » si divisible par 3, « Buzz » si divisible par 5, « FizzBuzz » si par les deux, sinon le nombre.",
    starter: "# FizzBuzz de 1 à 15\n",
    solution: 'for i in range(1, 16):\n    if i % 3 == 0 and i % 5 == 0:\n        print("FizzBuzz")\n    elif i % 3 == 0:\n        print("Fizz")\n    elif i % 5 == 0:\n        print("Buzz")\n    else:\n        print(i)',
    hint: "Teste d'abord le cas divisible par 3 ET 5, puis 3, puis 5, sinon le nombre.",
    expected: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz",
  },

  /* --------------------------------- SQL --------------------------------- */
  {
    id: "sql-calc",
    title: "Un calcul",
    lang: "sql",
    difficulty: "Facile",
    concept: "SELECT & calculs",
    prompt: "Affiche le résultat de 2 + 3 dans une colonne nommée resultat.",
    starter: "SELECT 2 + 3 AS resultat;",
    solution: "SELECT 2 + 3 AS resultat;",
    hint: "La requête est déjà prête : exécute-la !",
    check: (out) => out.includes("5"),
  },
  {
    id: "sql-select",
    title: "Lire une table",
    lang: "sql",
    difficulty: "Facile",
    concept: "SELECT & FROM",
    prompt: "La table users existe avec une ligne ('Alex'). Affiche tous les noms (nom).",
    starter: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\n-- Affiche la colonne nom\n",
    solution: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\nSELECT nom FROM users;",
    hint: "Ajoute SELECT nom FROM users; à la fin.",
    check: (out) => out.includes("Alex"),
  },
  {
    id: "sql-count",
    title: "Compter les lignes",
    lang: "sql",
    difficulty: "Moyen",
    concept: "COUNT()",
    prompt: "Compte le nombre d'utilisateurs dans la table users (résultat : 2).",
    starter: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\nINSERT INTO users VALUES (2, 'Lina');\n-- Compte les utilisateurs\n",
    solution: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\nINSERT INTO users VALUES (2, 'Lina');\nSELECT COUNT(*) AS total FROM users;",
    hint: "Utilise SELECT COUNT(*) AS total FROM users;",
    check: (out) => out.includes("2"),
  },
  {
    id: "sql-filtre",
    title: "Filtrer avec WHERE",
    lang: "sql",
    difficulty: "Moyen",
    concept: "WHERE",
    prompt: "Affiche uniquement les noms des utilisateurs majeurs (age >= 18).",
    starter: "CREATE TABLE users (id INT, nom TEXT, age INT);\nINSERT INTO users VALUES (1, 'Alex', 25);\nINSERT INTO users VALUES (2, 'Lina', 17);\n-- Affiche les noms des majeurs\n",
    solution: "CREATE TABLE users (id INT, nom TEXT, age INT);\nINSERT INTO users VALUES (1, 'Alex', 25);\nINSERT INTO users VALUES (2, 'Lina', 17);\nSELECT nom FROM users WHERE age >= 18;",
    hint: "Ajoute WHERE age >= 18 après le FROM users.",
    check: (out) => out.includes("Alex"),
  },
  {
    id: "sql-moyenne",
    title: "Calculer une moyenne",
    lang: "sql",
    difficulty: "Moyen",
    concept: "AVG()",
    prompt: "Affiche la moyenne des notes (résultat : 10).",
    starter: "CREATE TABLE notes (id INT, valeur INT);\nINSERT INTO notes VALUES (1, 10);\nINSERT INTO notes VALUES (2, 20);\nINSERT INTO notes VALUES (3, 0);\n-- Affiche la moyenne des notes\n",
    solution: "CREATE TABLE notes (id INT, valeur INT);\nINSERT INTO notes VALUES (1, 10);\nINSERT INTO notes VALUES (2, 20);\nINSERT INTO notes VALUES (3, 0);\nSELECT AVG(valeur) AS moyenne FROM notes;",
    hint: "Utilise SELECT AVG(valeur) AS moyenne FROM notes;",
    check: (out) => out.includes("10"),
  },
  {
    id: "sql-tri",
    title: "Trier les résultats",
    lang: "sql",
    difficulty: "Moyen",
    concept: "ORDER BY",
    prompt: "Affiche les noms du plus âgé au plus jeune (ordre décroissant).",
    starter: "CREATE TABLE users (id INT, nom TEXT, age INT);\nINSERT INTO users VALUES (1, 'Alex', 25);\nINSERT INTO users VALUES (2, 'Lina', 30);\n-- Affiche les noms triés par age décroissant\n",
    solution: "CREATE TABLE users (id INT, nom TEXT, age INT);\nINSERT INTO users VALUES (1, 'Alex', 25);\nINSERT INTO users VALUES (2, 'Lina', 30);\nSELECT nom FROM users ORDER BY age DESC;",
    hint: "Ajoute ORDER BY age DESC après le FROM users.",
    check: (out) => out.includes("Lina"),
  },
  {
    id: "sql-insert",
    title: "Ajouter puis compter",
    lang: "sql",
    difficulty: "Difficile",
    concept: "INSERT & COUNT",
    prompt: "Ajoute l'utilisateur 'Sam' (id 3), puis affiche le nombre total d'utilisateurs (résultat : 3).",
    starter: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\nINSERT INTO users VALUES (2, 'Lina');\n-- Ajoute 'Sam' (id 3) puis compte les utilisateurs\n",
    solution: "CREATE TABLE users (id INT, nom TEXT);\nINSERT INTO users VALUES (1, 'Alex');\nINSERT INTO users VALUES (2, 'Lina');\nINSERT INTO users VALUES (3, 'Sam');\nSELECT COUNT(*) AS total FROM users;",
    hint: "Ajoute INSERT INTO users VALUES (3, 'Sam'); puis SELECT COUNT(*) AS total FROM users;",
    check: (out) => out.includes("3"),
  },

  /* --------------------------------- Java --------------------------------- */
  {
    id: "java-hello",
    title: "Hello World",
    lang: "java",
    difficulty: "Facile",
    concept: "System.out.println",
    prompt: "Complète le programme pour qu'il affiche « Bonjour le monde ! ».",
    starter: "class Programme {\n    public static void main(String[] args) {\n        // affiche le message\n    }\n}",
    solution: 'class Programme {\n    public static void main(String[] args) {\n        System.out.println("Bonjour le monde !");\n    }\n}',
    hint: 'Utilise System.out.println("Bonjour le monde !");',
  },
  {
    id: "java-carre",
    title: "Méthode carré",
    lang: "java",
    difficulty: "Moyen",
    concept: "Méthodes & return",
    prompt: "Complète la méthode carre pour qu'elle renvoie n * n.",
    starter: "class Outils {\n    static int carre(int n) {\n        // renvoie n * n\n        return 0;\n    }\n}",
    solution: "class Outils {\n    static int carre(int n) {\n        return n * n;\n    }\n}",
    hint: "Remplace return 0; par return n * n;",
  },
  {
    id: "java-conditions",
    title: "Reçu ou à refaire",
    lang: "java",
    difficulty: "Facile",
    concept: "if / else",
    prompt: "Affiche « Reçu » si la note est >= 10, sinon « À refaire ».",
    starter: "class Programme {\n    public static void main(String[] args) {\n        int note = 14;\n        // affiche Reçu ou À refaire\n    }\n}",
    solution: 'class Programme {\n    public static void main(String[] args) {\n        int note = 14;\n        if (note >= 10) {\n            System.out.println("Reçu");\n        } else {\n            System.out.println("À refaire");\n        }\n    }\n}',
    hint: "Un if (note >= 10) { ... } else { ... } autour de deux println.",
  },
  {
    id: "java-boucle",
    title: "Compte de 1 à 5",
    lang: "java",
    difficulty: "Facile",
    concept: "Boucle for",
    prompt: "Affiche les nombres de 1 à 5, un par ligne.",
    starter: "class Programme {\n    public static void main(String[] args) {\n        // affiche les nombres de 1 à 5\n    }\n}",
    solution: "class Programme {\n    public static void main(String[] args) {\n        for (int i = 1; i <= 5; i++) {\n            System.out.println(i);\n        }\n    }\n}",
    hint: "Une boucle for (int i = 1; i <= 5; i++) avec un println(i) à l'intérieur.",
  },
  {
    id: "java-classe",
    title: "Une classe Voiture",
    lang: "java",
    difficulty: "Difficile",
    concept: "Classes & méthodes",
    prompt: "Ajoute une méthode klaxonner() qui affiche « Tut ! », crée une voiture et appelle la méthode.",
    starter: "class Voiture {\n    String couleur;\n\n    // ajoute la méthode klaxonner\n}\n\nclass Programme {\n    public static void main(String[] args) {\n        // crée une voiture et la fait klaxonner\n    }\n}",
    solution: 'class Voiture {\n    String couleur;\n\n    void klaxonner() {\n        System.out.println("Tut !");\n    }\n}\n\nclass Programme {\n    public static void main(String[] args) {\n        Voiture v = new Voiture();\n        v.klaxonner();\n    }\n}',
    hint: "Définis void klaxonner() avec un println, puis dans main : Voiture v = new Voiture(); v.klaxonner();",
  },
  {
    id: "java-array",
    title: "Somme d'un tableau",
    lang: "java",
    difficulty: "Moyen",
    concept: "Tableaux",
    prompt: "Calcule et affiche la somme des notes du tableau (résultat : 45).",
    starter: "class Programme {\n    public static void main(String[] args) {\n        int[] notes = {12, 15, 18};\n        int total = 0;\n        // additionne les notes et affiche total\n    }\n}",
    solution: "class Programme {\n    public static void main(String[] args) {\n        int[] notes = {12, 15, 18};\n        int total = 0;\n        for (int i = 0; i < notes.length; i++) {\n            total += notes[i];\n        }\n        System.out.println(total);\n    }\n}",
    hint: "Boucle for sur le tableau avec notes.length et ajoute notes[i] à total.",
  },

  /* ---------------------------------- C ---------------------------------- */
  {
    id: "c-hello",
    title: "Hello World",
    lang: "c",
    difficulty: "Facile",
    concept: "printf",
    prompt: "Complète le programme pour qu'il affiche « Bonjour le monde ! ».",
    starter: "#include <stdio.h>\n\nint main(void) {\n    // affiche le message\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nint main(void) {\n    printf("Bonjour le monde !\\n");\n    return 0;\n}',
    hint: 'Utilise printf("Bonjour le monde !\\n");',
  },
  {
    id: "c-somme",
    title: "La somme",
    lang: "c",
    difficulty: "Facile",
    concept: "printf & format",
    prompt: "Affiche la somme de 5 et 3 avec printf (résultat : 8).",
    starter: "#include <stdio.h>\n\nint main(void) {\n    // affiche la somme\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nint main(void) {\n    printf("%d\\n", 5 + 3);\n    return 0;\n}',
    hint: 'Utilise printf("%d\\n", 5 + 3);',
  },
  {
    id: "c-conditions",
    title: "Majeur ou mineur",
    lang: "c",
    difficulty: "Facile",
    concept: "if / else",
    prompt: "Affiche « Majeur » si l'âge est >= 18, sinon « Mineur ».",
    starter: "#include <stdio.h>\n\nint main(void) {\n    int age = 20;\n    // affiche Majeur ou Mineur\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nint main(void) {\n    int age = 20;\n    if (age >= 18) {\n        printf("Majeur\\n");\n    } else {\n        printf("Mineur\\n");\n    }\n    return 0;\n}',
    hint: "Un if (age >= 18) { ... } else { ... } avec deux printf.",
  },
  {
    id: "c-boucle",
    title: "Compte de 1 à 5",
    lang: "c",
    difficulty: "Facile",
    concept: "Boucle for",
    prompt: "Affiche les nombres de 1 à 5, un par ligne.",
    starter: "#include <stdio.h>\n\nint main(void) {\n    // affiche les nombres de 1 à 5\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nint main(void) {\n    for (int i = 1; i <= 5; i++) {\n        printf("%d\\n", i);\n    }\n    return 0;\n}',
    hint: 'Une boucle for avec printf("%d\\n", i); à l\'intérieur.',
  },
  {
    id: "c-pointeur",
    title: "Jouer avec un pointeur",
    lang: "c",
    difficulty: "Difficile",
    concept: "Pointeurs",
    prompt: "Crée un pointeur p vers x, puis modifie x à 20 en passant par le pointeur et affiche x.",
    starter: "#include <stdio.h>\n\nint main(void) {\n    int x = 10;\n    // crée un pointeur vers x, passe x à 20 via le pointeur, affiche x\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nint main(void) {\n    int x = 10;\n    int *p = &x;\n    *p = 20;\n    printf("%d\\n", x);\n    return 0;\n}',
    hint: "int *p = &x; puis *p = 20; modifie x via son adresse.",
  },
  {
    id: "c-struct",
    title: "Une structure Point",
    lang: "c",
    difficulty: "Difficile",
    concept: "Structures",
    prompt: "Définis une struct Point avec x et y, crée un point (10, 20) et affiche ses coordonnées.",
    starter: "#include <stdio.h>\n\n// définit la struct Point\n\nint main(void) {\n    // crée un point et affiche ses coordonnées\n    return 0;\n}",
    solution: '#include <stdio.h>\n\nstruct Point {\n    int x;\n    int y;\n};\n\nint main(void) {\n    struct Point p;\n    p.x = 10;\n    p.y = 20;\n    printf("%d, %d\\n", p.x, p.y);\n    return 0;\n}',
    hint: "struct Point { int x; int y; }; puis struct Point p; et on accède avec p.x, p.y.",
  },
];
